/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'JEE' : IDL.Null,
  'NEET' : IDL.Null,
  'Class10' : IDL.Null,
  'Class12' : IDL.Null,
});
export const QABankEntry = IDL.Record({
  'question' : IDL.Text,
  'subject' : IDL.Text,
  'answer' : IDL.Text,
  'category' : Category,
});
export const QuestionPaper = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'year' : IDL.Nat,
  'solutionUrl' : IDL.Opt(IDL.Text),
});
export const Chapter = IDL.Record({
  'url' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'chapters' : IDL.Vec(Chapter),
});
export const SyllabusEntry = IDL.Record({
  'subjects' : IDL.Vec(Subject),
  'category' : Category,
});
export const GlossaryTerm = IDL.Record({
  'subject' : IDL.Text,
  'term' : IDL.Text,
  'definition' : IDL.Text,
});

export const idlService = IDL.Service({
  'getQABankEntriesBySubject' : IDL.Func(
      [Category, IDL.Text],
      [IDL.Vec(QABankEntry)],
      ['query'],
    ),
  'getQuestionPapers' : IDL.Func(
      [Category, IDL.Text],
      [IDL.Vec(QuestionPaper)],
      ['query'],
    ),
  'getSyllabus' : IDL.Func([Category], [SyllabusEntry], ['query']),
  'searchGlossary' : IDL.Func([IDL.Text], [IDL.Vec(GlossaryTerm)], ['query']),
  'searchQABank' : IDL.Func([IDL.Text], [IDL.Vec(QABankEntry)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'JEE' : IDL.Null,
    'NEET' : IDL.Null,
    'Class10' : IDL.Null,
    'Class12' : IDL.Null,
  });
  const QABankEntry = IDL.Record({
    'question' : IDL.Text,
    'subject' : IDL.Text,
    'answer' : IDL.Text,
    'category' : Category,
  });
  const QuestionPaper = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'year' : IDL.Nat,
    'solutionUrl' : IDL.Opt(IDL.Text),
  });
  const Chapter = IDL.Record({ 'url' : IDL.Opt(IDL.Text), 'name' : IDL.Text });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'chapters' : IDL.Vec(Chapter),
  });
  const SyllabusEntry = IDL.Record({
    'subjects' : IDL.Vec(Subject),
    'category' : Category,
  });
  const GlossaryTerm = IDL.Record({
    'subject' : IDL.Text,
    'term' : IDL.Text,
    'definition' : IDL.Text,
  });
  
  return IDL.Service({
    'getQABankEntriesBySubject' : IDL.Func(
        [Category, IDL.Text],
        [IDL.Vec(QABankEntry)],
        ['query'],
      ),
    'getQuestionPapers' : IDL.Func(
        [Category, IDL.Text],
        [IDL.Vec(QuestionPaper)],
        ['query'],
      ),
    'getSyllabus' : IDL.Func([Category], [SyllabusEntry], ['query']),
    'searchGlossary' : IDL.Func([IDL.Text], [IDL.Vec(GlossaryTerm)], ['query']),
    'searchQABank' : IDL.Func([IDL.Text], [IDL.Vec(QABankEntry)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };