/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SyllabusEntry {
    subjects: Array<Subject>;
    category: Category;
}
export interface GlossaryTerm {
    subject: string;
    term: string;
    definition: string;
}
export interface QuestionPaper {
    url: string;
    title: string;
    year: bigint;
    solutionUrl?: string;
}
export interface QABankEntry {
    question: string;
    subject: string;
    answer: string;
    category: Category;
}
export interface Subject {
    id: bigint;
    name: string;
    chapters: Array<Chapter>;
}
export interface Chapter {
    url?: string;
    name: string;
}
export enum Category {
    JEE = "JEE",
    NEET = "NEET",
    Class10 = "Class10",
    Class12 = "Class12"
}
export interface backendInterface {
    getQABankEntriesBySubject(category: Category, subject: string): Promise<Array<QABankEntry>>;
    getQuestionPapers(category: Category, subject: string): Promise<Array<QuestionPaper>>;
    getSyllabus(category: Category): Promise<SyllabusEntry>;
    searchGlossary(keyword: string): Promise<Array<GlossaryTerm>>;
    searchQABank(keyword: string): Promise<Array<QABankEntry>>;
}
import type { Category as _Category, Chapter as _Chapter, QABankEntry as _QABankEntry, QuestionPaper as _QuestionPaper, Subject as _Subject, SyllabusEntry as _SyllabusEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getQABankEntriesBySubject(arg0: Category, arg1: string): Promise<Array<QABankEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQABankEntriesBySubject(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQABankEntriesBySubject(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionPapers(arg0: Category, arg1: string): Promise<Array<QuestionPaper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionPapers(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionPapers(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSyllabus(arg0: Category): Promise<SyllabusEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getSyllabus(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SyllabusEntry_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSyllabus(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SyllabusEntry_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchGlossary(arg0: string): Promise<Array<GlossaryTerm>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchGlossary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchGlossary(arg0);
            return result;
        }
    }
    async searchQABank(arg0: string): Promise<Array<QABankEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchQABank(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchQABank(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Chapter_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Chapter): Chapter {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_QABankEntry_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QABankEntry): QABankEntry {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionPaper_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionPaper): QuestionPaper {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_SyllabusEntry_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SyllabusEntry): SyllabusEntry {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    title: string;
    year: bigint;
    solutionUrl: [] | [string];
}): {
    url: string;
    title: string;
    year: bigint;
    solutionUrl?: string;
} {
    return {
        url: value.url,
        title: value.title,
        year: value.year,
        solutionUrl: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.solutionUrl))
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subjects: Array<_Subject>;
    category: _Category;
}): {
    subjects: Array<Subject>;
    category: Category;
} {
    return {
        subjects: from_candid_vec_n14(_uploadFile, _downloadFile, value.subjects),
        category: from_candid_Category_n6(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    chapters: Array<_Chapter>;
}): {
    id: bigint;
    name: string;
    chapters: Array<Chapter>;
} {
    return {
        id: value.id,
        name: value.name,
        chapters: from_candid_vec_n17(_uploadFile, _downloadFile, value.chapters)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: [] | [string];
    name: string;
}): {
    url?: string;
    name: string;
} {
    return {
        url: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.url)),
        name: value.name
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    question: string;
    subject: string;
    answer: string;
    category: _Category;
}): {
    question: string;
    subject: string;
    answer: string;
    category: Category;
} {
    return {
        question: value.question,
        subject: value.subject,
        answer: value.answer,
        category: from_candid_Category_n6(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    JEE: null;
} | {
    NEET: null;
} | {
    Class10: null;
} | {
    Class12: null;
}): Category {
    return "JEE" in value ? Category.JEE : "NEET" in value ? Category.NEET : "Class10" in value ? Category.Class10 : "Class12" in value ? Category.Class12 : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subject>): Array<Subject> {
    return value.map((x)=>from_candid_Subject_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Chapter>): Array<Chapter> {
    return value.map((x)=>from_candid_Chapter_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QABankEntry>): Array<QABankEntry> {
    return value.map((x)=>from_candid_QABankEntry_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuestionPaper>): Array<QuestionPaper> {
    return value.map((x)=>from_candid_QuestionPaper_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    JEE: null;
} | {
    NEET: null;
} | {
    Class10: null;
} | {
    Class12: null;
} {
    return value == Category.JEE ? {
        JEE: null
    } : value == Category.NEET ? {
        NEET: null
    } : value == Category.Class10 ? {
        Class10: null
    } : value == Category.Class12 ? {
        Class12: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
